### ISSUE TITLE
TRACE +0.109 Timed out waiting for packet header

### ISSUE THREAD

**Issue by EurophiaDealer** [puckk/CJMCU-3212#1]
I can't upload the ESP sketch, and its giving me this errors: 
TRACE +0.000 Write 46 bytes:
    c000082400000000 0007071220555555 | ...$........ UUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    5555555555555555 5555555555c0     | UUUUUUUUUUUUU.
TRACE +0.109 Timed out waiting for packet header

Iam using the ESPTOOL on win. 
I connected the two metal circles, without sucess.
Note: Every time that i start trying to upload the skecht my board blinks a blue light.
This is the command am using> 

esptool.py --trace --baud 150200 --port COM5 write_flash 0x00000 C:/Users/MyUser/Desktop/esp8266_wifi_duck_4mb.bin --flash_size 4MB --flash_mode dio --flash_freq 40m

**Comment by bhiggins-2** [comment]
I'm experiencing the same behavior, I've also tried changing the baud rate to 115200 without success. my command is:
`python esptool.py --trace   --baud 115200 --port COM5 write_flash 0x00000 esp8266_wifi_duck_4mb.bin --flash_size 4MB --flash_mode dio --flash_freq 40m`

Also, last line before execution completes is:
`A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header`

**Comment by puckk** [comment]
Bridge metallic circles
Connect to USB
Run script
When says"connecting" release bridge

**Comment by bhiggins-2** [comment]
Hey, EuphoriaDealer, I've found a solution to successfully flash the ESP8266. Instead of his CLI Python-based flasher, NODEMCU has a GUI-based flasher here that worked for me. I'll put it in a google drive folder for you here.
`https://drive.google.com/open?id=1Gfi9OF3827Y__iTiRg8PsNZjoelHBXYq`

In the program you can configure the parameters as he stated in his python command, and I had the bridge connected before connecting to usb and the entire time during the flash. In other words, I didn't disconnect the bridge until the flash was over. Let me know if this works for you!

**Comment by code2319** [comment]
`C:\Python37\Scripts\esptool.py --trace --baud 115200 --port COM5 write_flash 0x00000 esp8266_wifi_duck_4mb.bin --flash_size 4MB --flash_mode dio --flash_freq 40m`

`Traceback (most recent call last):
  File "C:\Python37\Scripts\esptool.py-script.py", line 11, in <module>
    load_entry_point('esptool==2.8', 'console_scripts', 'esptool.py')()
  File "C:\Python37\lib\site-packages\esptool.py", line 3194, in _main
    main()
  File "C:\Python37\lib\site-packages\esptool.py", line 2883, in main
    esp = ESPLoader.detect_chip(each_port, initial_baud, args.before, args.trace)
  File "C:\Python37\lib\site-packages\esptool.py", line 274, in detect_chip
    detect_port.connect(connect_mode)
  File "C:\Python37\lib\site-packages\esptool.py", line 475, in connect
    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
  File "C:\Python37\lib\site-packages\esptool.py", line 455, in _connect_attempt
    self.sync()
  File "C:\Python37\lib\site-packages\esptool.py", line 394, in sync
    timeout=SYNC_TIMEOUT)
  File "C:\Python37\lib\site-packages\esptool.py", line 337, in command
    self.write(pkt)
  File "C:\Python37\lib\site-packages\esptool.py", line 300, in write
    self._port.write(buf)
  File "C:\Python37\lib\site-packages\serial\serialwin32.py", line 323, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout`

with the bridge and without it does not work, also changing the baud also does not work
How to fix the error?
